# Generated by Django 3.0.7 on 2020-06-28 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='builddate',
            field=models.IntegerField(blank=True, default=2019),
        ),
        migrations.AddField(
            model_name='listing',
            name='elevator',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='floorcount',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='floornumber',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='frontage',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='heatIsolation',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2),
        ),
        migrations.AddField(
            model_name='listing',
            name='heating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=1),
        ),
        migrations.AddField(
            model_name='listing',
            name='livingroom',
            field=models.DecimalField(blank=True, decimal_places=1, default=1, max_digits=2),
        ),
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
