# Generated by Django 3.0.7 on 2020-06-28 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200628_1938'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='bathrooms',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='elevator',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floorcount',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='floornumber',
            field=models.IntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='listing',
            name='frontage',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='heatIsolation',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='heating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='listing',
            name='livingroom',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
